apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configmap
  labels:
    app: application
    component: application
data:
  application.ini: |-
    [database]
    url = postgresql+psycopg2://postgres:admin@123@0.0.0.0:5432/app_db?options=-csearch_path=app_db
    connect_args = True
    use_connection_pooling = False
    pool_pre_ping = True
    pool_size = 20
    pool_timeout = 120
    pool_recycle = 60

    [gunicorn]
    config_file = /project_name/configs/gunicorn.py

    [flask]
    base_url = /application/api

    [testing]
    testing = False
